### ISSUE TITLE
hide secret in auth.js

### ISSUE THREAD

**Issue by dotdlew** [LyleKilson/wallpaper-market#12]
we need to securely hide the token secret in auth.js

**Comment by dotdlew** [comment]
also, the secret needs to be something stronger than "mysecretsshhhhh"

**Comment by LyleKilson** [comment]
What about "1234678"?

**Comment by dotdlew** [comment]
working on hiding secret

JWT_SECRET=lfgLYTs48DiIyl0YukF4ZwXgnJf3z1Sq
